apiVersion: apps/v1
kind: Deployment
metadata:
  name: zenthor-ai-cripto
spec:
  replicas: 2  # teszteléshez javasolt 2 példány indítása
  selector:
    matchLabels:
      app: zenthor-ai-cripto
  template:
    metadata:
      labels:
        app: zenthor-ai-cripto
    spec:
      containers:
      - name: zenthor-ai-cripto
        image: zenthor-ai-cripto:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
      restartPolicy: Always
