apiVersion: v1
kind: Service
metadata:
  name: zenthor-ai-cripto
spec:
  selector:
    app: zenthor-ai-cripto
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080  # Kívülről elérhetővé teszi
  type: NodePort
