apiVersion: v1
kind: Service
metadata:
  name: zenthor-ai-cripto
  labels:
    app.kubernetes.io/name: zenthor-ai-cripto
    app.kubernetes.io/version: "0.1"
spec:
  replicas: 2
  selector:
    app: zenthor-ai-cripto
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30080  # Kívülről elérhetővé teszi
  type: NodePort


