name: CI for zenthor-ai-cripto

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    # A container blokk biztosítja, hogy a CI futtatási környezet
    # a python:3.13-slim image-ben legyen, ami könnyű és optimalizált,
    # ezáltal jobban tükrözi a production (Kubernetes) környezetet.
    container:
      image: python:3.13-slim
      options: --privileged -v /var/run/docker.sock:/var/run/docker.sock

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Cache pip dependencies
        uses: actions/cache@v4  # Frissítve a v4-es verzióra a hosszú távú kompatibilitás miatt
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

     # - name: Set up Python 3.13 # Beállítja a Python környezetet
     - name: Set up Python 3.11 # Beállítja a Python környezetet
        uses: actions/setup-python@v2
        with:
         #python-version: 3.13
          python-version: 3.11

      - name: Függőségek telepítése
        run: pip install --no-cache-dir -r requirements.txt
        timeout-minutes: 5

      - name: Run tests
        run: |
          # Futtasd a teszteket, ha készítesz például unittest-eket
          python -m unittest discover

      - name: Install Docker CLI
        run: |
          apt-get update && apt-get install -y docker.io

      - name: Build Docker image # Buildelés
        run: docker build -t zenthor-ai-cripto .
